# Ejercicios de NumPy (solución)

Resolver en celdas contiguas de acuerdo con lo soliicado.

Importa la librería NumPy:

In [3]:
import numpy as np

Crear un arreglo NumPy que tenga la siguente estructura,

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

y asignarlo a la variable `m`.

In [9]:
m = np.array(range(1,16)).reshape(3,5).transpose()
print(m)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Obtener la forma del arreglo `m`:

In [10]:
m.shape

(5, 3)

Selecciona la segunda columna del arreglo `m`:

In [11]:
m[:,1]

array([ 6,  7,  8,  9, 10])

Crear un vector con los valores del 15 al 55, y almacénalo en la variable `array2`:

In [16]:
array2 = np.array(range(15, 56))
print(array2)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


Asigna el valor 23 a la quinta posicion de `array2`:

In [17]:
array2[4] = 23
print(array2)

[15 16 17 18 23 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


Invertir el `array2`, es decir `[55,54,....,15]`:

In [55]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crear una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares del `array2`, asignala a la variable `matriz_diag`.

In [56]:
matriz_diag = np.diag(array2[:5])
print(matriz_diag)

[[15  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  0 17  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 23]]


Imprime el numero de dimensiones de `matriz_diag`:

In [60]:
print(matriz_diag.ndim)

2


Crear una matriz con números aleatorios de tamaño 5x3 (5 filas por 3 columnas), denomínala `matriz`:

In [93]:
matriz = np.random.randint(10, size=(5,3))
print(matriz)

[[9 5 5]
 [2 9 3]
 [2 8 8]
 [1 2 7]
 [0 1 6]]


Multiplica `matriz_diag` por `matriz`:

In [103]:
print(matriz_diag.dot(matriz))

[[135  75  75]
 [ 32 144  48]
 [ 34 136 136]
 [ 18  36 126]
 [  0  23 138]]


Escribe una función que retorne `True` cuando ninguno de los elementos de una matriz dada (`ndarray`) es cero. De lo contrario, debe retorne la posición de la primera ocurrencia del valor cero.

__NOTA__: La función [`numpy.all`](https://numpy.org/doc/stable/reference/generated/numpy.all.html) podría ayudar en la resolución de este problema.

In [114]:
def no_tiene_ceros(m):
    if np.all(m):
        return True
    else:
        f, c = m.shape
        for i in range(f):
            for j in range(c):
                if not m[i][j]:
                    return (i, j)


no_tiene_ceros(matriz)

(4, 0)

Escribe una función que retorne `True` cuando ninguno de los elementos de una matriz dada (`numpy.ndarray`) es nulo (`np.nan`). De lo contrario, debe retornar la posición de la primera ocurrencia del valor `np.nan`.

__NOTA__: La función [`numpy.isnan`](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html) podría ayudar en la resolución de este problema.

In [131]:
def no_contiene_nulos(m):
    m_logical = np.isnan(m)
    f, c = m_logical.shape
    for i in range(f):
        for j in range(c):
            if m_logical[i][j]:
                return (i, j)
    return True


m = np.genfromtxt('./data/array_b.txt',  delimiter=',')
print(m)
print('\nPrimer nulo: {}'.format(no_contiene_nulos(m)))

[[ 1.  2.  3.]
 [43.  2. nan]
 [nan  1.  1.]
 [ 0.  1.  1.]]

Primer nulo: (1, 2)


Escribe una función que realice la extracción de todos los números de una matriz que son más grandes que un número especificado. La función deberá generar un archivo de texto (`.txt`) con los números extraidos.

__NOTA__: La función [`numpy.savetxt`](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html) podría ayudar en la resolución de este problema.

In [142]:
def mayores_que(matriz, x):
    query = matriz > x
    mayores = matriz[query]
    fname = 'mayores_que_{}.txt'.format(x)
    np.savetxt(fname, mayores, fmt='%i')

mayores_que(matriz, 6)

Diseña una función para encontrar valores comunes entre dos arreglos. La función debe retornar los valores ordenados de forma decreciente.

__NOTA__: La objeto [`numpy.instersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html) podría ayudar en la resolución de este problema.

Escribe una sentencia para obtener la fecha actual.

__NOTA__: El objeto [`datetime64`](https://numpy.org/doc/stable/reference/arrays.datetime.html) podría ayudar en la resolución de este problema.

Diseña una función que, dado un escalar, encuentre el valor más cercano en un vector.

__NOTA__: La función [`numpy.argmin()`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) podría ayudar en la construcción de la resolución del problema.

Diseña una función que encuentre el valor más frecuente en una arreglo.

Considere 2 arreglos A y B de forma (8,3) y (2,2), respectivamente. Diseña una función que encuentre las filas de A que contiene los elementos de B, independiente del orden de los elementos de B.