# NumPy: Numerical Python

[NumPy](https://numpy.org)

- Es una biblioteca de Python para computación científica.
- Contiene funciones para trabajar en el dominio del álgebra lineal, la transformación de Fourier y las matrices.
- Es un proyecto de código abierto y puede ser utilizado libremente.

### Por qué usar NumPy?

Las lista de Python son utiles como matrices, pero son lentas de procesar.

NumPy proporciona un __objeto tipo arreglo__ que es hasta 50 veces más rápido que las listas de Python.
- La librería está optimizado para trabajar con las últimas arquitecturas de CPU.
- Las matrices NumPy se almacenan en un lugar continuo de la memoria a diferencia de las listas, por lo que los procesos pueden acceder a ellas y manipularlas de forma eficiente.
- El arreglo `ndarray` de NumPy, proporciona diversas funciones que permiten que el trabajo sea más sencillo.

In [124]:
import numpy as np    # Importando la libreria

print(np.__version__)

1.21.2


## Crear arreglos

Una arreglo de NumPy es una grilla de valores, 
- todos del mismo tipo, 
- está indexada por una tupla de números enteros no negativos,
- el número de dimensiones es el rango de la matriz,
- la forma de una matriz es una tupla de números enteros con el tamaño de la matriz a lo largo de cada dimensión.

Es posible crear un objeto `ndarray` desde una lista de Python, usando la función `array()`.

In [125]:
mi_array = np.array([4,5,3])
type(mi_array)

numpy.ndarray

In [126]:
mi_array

array([4, 5, 3])

Es posible crear distintos tipos de arreglos:
- 0D o escalar
- 1D
- 2D o mátriz, que contiene arreglos 
- 3D, que contiene arreglos 2D
- Multidimensionales

In [127]:
# array 0-D o escalar
np.array(34)

array(34)

In [128]:
# array 1-D
np.array([1, 2, 3, 4, 5])


array([1, 2, 3, 4, 5])

In [129]:
# array 2-D
array_2D = np.array([                 
    [1,2,3], 
    [4,5,6]
    ])
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
# array 3-D
array_3D = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[11, 12, 13], [14, 15, 16]],
    [[21, 22, 13], [24, 25, 26]]
    ])
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 13],
        [24, 25, 26]]])

## Dimensión y tamaño

Los arreglos de NumPy contienen el atributo `ndarray.ndim` que retorna un entero con la dimensión de un arreglo.

In [131]:
array_3D.ndim

3

La forma de un arreglo corresponde al número de elementos en cada dimensión. El atributo `ndarray.shape` retorna una tupla con los elementos de cada dimensión.

In [132]:
array_3D.shape

(3, 2, 3)

## Funciones para crear arreglos

In [133]:
# arreglo de ceros
np.zeros((3,2))             

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [134]:
# matriz de unos
np.ones((2))

array([1., 1.])

In [135]:
# matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
# arreglo de constantes
np.full((3,3), .5)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [137]:
# arreglo de valores aleatorios, entre 0 y 1
np.random.random((3,2))

array([[0.11695524, 0.88742992],
       [0.29325521, 0.53635577],
       [0.89745215, 0.82730587]])

In [138]:
# arreglo de valores aleatorios, entre mínimo (incl.) y un máximo (excl.)
np.random.randint(1, high=10, size=(4,3))

array([[9, 1, 8],
       [2, 2, 5],
       [9, 2, 4],
       [3, 6, 9]])

Otros método para la creación de arreglos puede ser consultado [aquí](https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation).

## Importar arreglo desde archivos

In [139]:
!cat './dataset/array.txt'

1,2,3
43,2,3
34,1,1
0,1,1

La función `numpy.genfromtxt` carga datos desde un archivo de texto.

In [140]:
m = np.genfromtxt('./dataset/array.txt', delimiter=',')
m

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

Los valores perdidos pueden ser completado con el parámetro opcional `filling_values`.

In [141]:
m = np.genfromtxt('./dataset/array_b.txt', delimiter=',', filling_values=20)
m

array([[ 1.,  2.,  3.],
       [43.,  2., 20.],
       [20.,  1.,  1.],
       [ 0.,  1.,  1.]])

## Indexación de arreglos

NumPy ofrece diferentes formar para indexar arreglos.

- Slice (similar a Python)

In [142]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
# subarreglo 2 primeras filas y 2 primeras columnas
array_2D[0:2, 0:2]

array([[1, 2],
       [4, 5]])

- Slice (similar a Matlab)

In [144]:
# todos los elementos de la columna 1
array_2D[:, 1]

array([2, 5])

La __indexación de arreglo booleano__ permite elegir elementos arbitrarios de un arreglo.
- Se usa para seleccionar elementos que satisfacen una condición,

In [145]:
# encontrar elementos mayores que 2
idx_bool = m > 2  
idx_bool

array([[False, False,  True],
       [ True, False,  True],
       [ True, False, False],
       [False, False, False]])

Para obtener los elementos del arreglo original,

In [146]:
# IMPORTANTE ndim = 1
m[idx_bool]

array([ 3., 43., 20., 20.])

## Funciones matemáticas

In [147]:
x = np.array([
    [1,2],
    [3,4]
    ])
y = np.array([
    [5,6],
    [7,8]
    ])

- Suma de matrices

In [148]:
x + y
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

- Resta


In [149]:
x - y
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

- Multiplicación (elemento por elemento)

In [150]:
x * y
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

- Producto interno de vectores y matrices. El produto `dot` está disponible como una función,

In [151]:
z = np.array([9, 10])
np.dot(z, y)

array([115, 134])

o como un método de instancia del objeto,

In [152]:
z.dot(y)

array([115, 134])